
public void futureCF6() throws Exception {
		CompletableFuture<String> user = CompletableFuture.supplyAsync(new Supplier<String>() {
			
			public String get() {
				System.out.println("Enter user");
				Scanner in = new Scanner(System.in);
				String name = in.nextLine();
				return getUser(name);
			}
			
		}).thenApplyAsync(usr -> getCredit(usr), executor).thenApplyAsync(cred -> cred + doTransaction(cred), executor);
		CompletableFuture<Void> printer = user.thenAcceptAsync(System.out::println);
		CompletableFuture<Void> creditProcessed = printer.thenRunAsync(() -> System.out.println("Transaction completed"), executor);
		user.get();
	}
	
  futureCF6(); ///note that user.get() is blocking and no following thread can execute before get return.
  
  public String getUser(String name) {
		//get user from remote server;
		userName = name;
		try {
			Thread.sleep(2000);
		} catch (Exception e) {}
		System.out.println("User " + name + " Found!");
		return name;
	}
	
	public String getCredit(String user) {
		//get credit from remote server;
		try {
			Thread.sleep(2000);
		} catch (Exception e) {}
		System.out.println(user + " Credit Detail Request!");
		return "Credit:1000";
	}
	
	public String doTransaction(String credit) {
		try {
			Thread.sleep(2000);
		} catch(Exception e) {
		}
		String[] tokens = credit.split(":");
		System.out.println("Transaction request!");
		return ", After transaction 1000 - 100 = 900";
	}
